bot:
  welcome_message: |
    欢迎使用我们的互动小说Bot！
    这是一个让您沉浸在精彩故事中的互动体验。
    您可以通过做出不同的选择来影响故事的发展。
    
  help_message: |
    📖 互动小说Bot使用指南：
    
    /start - 开始新的故事
    /help - 显示帮助信息
    
    如何使用：
    1. 阅读每个章节的内容
    2. 根据提示做出选择
    3. 您的选择将影响故事的发展方向
    
  first_chapter: |
    第一章：神秘的来信
    
    一个平静的早晨，你收到了一封没有署名的信。信封上用优雅的字体写着你的名字，火漆印章透露出一丝神秘的气息。
    
    你要：
    A. 立即打开信封
    B. 仔细检查信封 